POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Titulo 2",
    "description": "primeiro video",
    "duration": 200
}

###

GET http://localhost:3333/videos

###

# Utilizando paramentros de buscar (QUERY)

GET http://localhost:3333/videos?search=node


###

PUT http://localhost:3333/videos/69adfc40-2c45-4c3f-a117-6f6d9c0a9373
Content-Type: application/json

{
    "title": "Titulo 01 - Node att",
    "description": "primeiro video",
    "duration": 200
}

###

DELETE http://localhost:3333/videos/69adfc40-2c45-4c3f-a117-6f6d9c0a9373